version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - MAX_FILE_SIZE_BYTES=${MAX_FILE_SIZE_BYTES:-10485760}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS:-.jpg,.jpeg,.png,.gif,.webp,.bmp}
      - PUBLIC_READ_ACCESS=${PUBLIC_READ_ACCESS:-true}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      migration:
        condition: service_completed_successfully  # Wait for migration to complete successfully
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-blazorauth}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration  # Use separate migration Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    command: >
      sh -c "
        echo '🚀 Starting database migration...' &&
        echo 'Connection: ${ConnectionStrings__DefaultConnection}' &&
        dotnet ef database update --verbose &&
        echo '✅ Migration completed successfully!'
      "
    networks:
      - app-network
    restart: "no"  # Migration should not restart after completion

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge